baseurl = "http://partokarwat.com/"
title = "Parto Karwat"
languageCode = "en-us"
theme = "hyde"

[params]
  themeColor = "theme-base-0b"
  description = "developing Android Apps"

[author]
  name = "Parto Karwat"

[taxonomies]
  tag = "tags"
  topic = "topics"
